-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 14:22:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw_trabalho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw_trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw_trabalho` DEFAULT CHARACTER SET utf8 ;
USE `dw_trabalho` ;

-- -----------------------------------------------------
-- Table `dw_trabalho`.`DIM_PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_trabalho`.`DIM_PRODUTOS` (
  `id` INT NOT NULL,
  `nome_produto` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_trabalho`.`DIM_CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_trabalho`.`DIM_CLIENTES` (
  `id` INT NOT NULL,
  `nome_cliente` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_trabalho`.`DIM_DATAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_trabalho`.`DIM_DATAS` (
  `id` INT NOT NULL,
  `data` DATE NOT NULL,
  `ano` INT NOT NULL,
  `mes` INT NOT NULL,
  `dia` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_trabalho`.`DIM_LOJAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_trabalho`.`DIM_LOJAS` (
  `id` INT NOT NULL,
  `nome_loja` VARCHAR(255) NOT NULL,
  `endereco_loja` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_trabalho`.`FATO_VENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_trabalho`.`FATO_VENDAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_data` INT NOT NULL,
  `id_loja` INT NOT NULL,
  `qt_vendida` INT NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_produto`
    FOREIGN KEY (`id`)
    REFERENCES `dw_trabalho`.`DIM_PRODUTOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id`)
    REFERENCES `dw_trabalho`.`DIM_CLIENTES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_date`
    FOREIGN KEY (`id`)
    REFERENCES `dw_trabalho`.`DIM_DATAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_loja`
    FOREIGN KEY (`id`)
    REFERENCES `dw_trabalho`.`DIM_LOJAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
